export const ROLE_SKILLS = {
  "Backend Engineer": ["Node.js", "Express", "REST APIs", "Databases", "Scaling"],
  "Frontend Engineer": ["React", "State Management", "UI/UX", "Performance", "Accessibility"],
  "Full Stack": ["Frontend", "Backend", "Databases", "APIs", "Deployment"],
  "DevOps Engineer": ["CI/CD", "Docker", "Kubernetes", "Monitoring", "Cloud Deployment"],
  "Cloud Engineer": ["AWS", "GCP", "Infrastructure", "Networking", "Security"],
  "Data Scientist": ["ML", "Statistics", "Data Cleaning", "Visualization", "Model Evaluation"],
  "AI Engineer": ["Deep Learning", "NLP", "Model Deployment", "Prompting", "MLOps"],
  "Mobile Developer": ["Flutter", "React Native", "State Management", "Performance", "Offline Sync"],
  "QA Engineer": ["Testing", "Automation", "Test Cases", "Bug Tracking", "Regression Testing"],
  "Cybersecurity": ["Network Security", "Encryption", "Threat Detection", "Authentication", "Risk Assessment"],
  "Product Manager": ["Roadmapping", "Prioritization", "User Research", "Metrics", "Stakeholder Management"],
  "UI/UX Designer": ["Wireframing", "Prototyping", "Usability", "Visual Design", "Accessibility"],
  "Database Engineer": ["SQL", "Indexing", "Normalization", "Replication", "Optimization"],
  "Software Architect": ["System Design", "Scalability", "Design Patterns", "Microservices", "Trade-offs"],
  "Blockchain Developer": ["Smart Contracts", "Web3", "Solidity", "Security", "DApps"],
  "Embedded Systems Engineer": ["C/C++", "Microcontrollers", "RTOS", "Hardware Interfaces", "Debugging"],
  "Machine Learning Engineer": ["Feature Engineering", "Model Training", "Deployment", "Evaluation", "MLOps"],
  "Data Engineer": ["ETL", "Pipelines", "SQL", "Data Warehousing", "Batch/Streaming"],
  "Network Engineer": ["Routing", "Switching", "TCP/IP", "DNS", "Troubleshooting"],
  "System Administrator": ["Linux", "Servers", "Scripting", "Monitoring", "User Management"],
  "Salesforce Developer": ["Apex", "LWC", "CRM", "Integrations", "Automation"],
  "Android Developer": ["Kotlin", "Jetpack", "UI", "Performance", "APIs"],
  "iOS Developer": ["Swift", "UIKit/SwiftUI", "Performance", "APIs", "App Architecture"],
  "Game Developer": ["Game Loops", "Physics", "Optimization", "C# / C++", "Assets"],
  "DevSecOps Engineer": ["Secure CI/CD", "Secrets Management", "Scanning", "Container Security", "Compliance"],
  "Business Analyst": ["Requirements", "Documentation", "Process Mapping", "Stakeholders", "Reporting"],
  "Support Engineer": ["Troubleshooting", "Logs", "Customer Handling", "SLA", "Root Cause Analysis"],
  "Site Reliability Engineer": ["Reliability", "Monitoring", "Incident Response", "Automation", "Scaling"],
  "Research Engineer": ["Experimentation", "Papers", "Prototyping", "Metrics", "Iteration"],
  "Technical Writer": ["Clarity", "Documentation", "Structure", "Examples", "Audience Awareness"],
  "General Programmer": ["Problem Solving", "DSA", "Debugging", "Code Quality", "System Thinking"],
};